# Generated by Django 4.2.5 on 2023-09-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('natural', 'NATURAL'), ('juridica', 'JURIDICA')], default='natural', max_length=10)),
                ('mail', models.CharField(max_length=255)),
                ('initialDonation', models.DecimalField(decimal_places=3, max_digits=19)),
            ],
        ),
    ]
