# Generated by Django 4.2.5 on 2023-09-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='mail',
            field=models.EmailField(max_length=200),
        ),
    ]
