# Generated by Django 4.1.7 on 2023-11-01 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation_project',
            name='nit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sponsor', to_field='nit'),
        ),
    ]
