# Generated by Django 4.2.5 on 2023-09-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sponsor_id_alter_sponsor_nit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('objective', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
