# Generated by Django 4.2.5 on 2023-09-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('florecimiento', 'FLORECIMIENTO'), ('organizacinal', 'ORGANIZACIONAL')], default='florecimiento', max_length=20),
        ),
    ]
