# Generated by Django 4.2.5 on 2023-11-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_doi_product_link_product_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='type',
            field=models.CharField(choices=[('Natural', 'NATURAL'), ('Juridica', 'JURIDICA')], default='natural', max_length=10),
        ),
    ]
