# Generated by Django 4.2.5 on 2023-10-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Florecimiento', 'FLORECIMIENTO'), ('Organizacional', 'ORGANIZACIONAL')], default='florecimiento', max_length=20),
        ),
    ]
