# Generated by Django 4.2.5 on 2023-11-14 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sponsor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='initial_donation',
        ),
    ]
