# Generated by Django 4.2.5 on 2023-10-02 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='initialDonation',
            new_name='initial_donation',
        ),
    ]
