# Generated by Django 4.2.6 on 2023-10-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_followup'),
        ('core', '0009_alter_donation_date'),
    ]

    operations = [
    ]
