# Generated by Django 4.2.5 on 2023-10-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_0008_followup_0009_alter_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='nit',
            field=models.IntegerField(unique=True),
        ),
    ]
