# Generated by Django 4.2.5 on 2023-10-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sponsor_id_alter_sponsor_nit'),
    ]

    operations = [
        migrations.CreateModel(
            name='investigation_project',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('objectives', models.TextField()),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('nit', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(related_name='events', to='core.sponsor'),
        ),
    ]
