# Generated by Django 4.2.5 on 2023-10-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_investigation_project_event_sponsors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sponsors',
        ),
    ]
