# Generated by Django 4.2.5 on 2023-10-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_investigation_project_sponsor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(default='activo', max_length=255),
        ),
    ]
