# Generated by Django 4.2.5 on 2023-10-11 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_sponsor_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='status',
        ),
    ]
