# Generated by Django 4.2.5 on 2023-10-15 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product'),
        ('core', '0014_event_sponsors'),
    ]

    operations = [
    ]
