# Generated by Django 4.2.5 on 2023-10-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_sponsor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='status',
            field=models.CharField(default='activo', max_length=255),
        ),
    ]
