# Generated by Django 4.2.5 on 2023-10-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_sponsor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
