# Generated by Django 4.2.5 on 2023-10-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_0010_product_0014_event_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation_project',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.investigation_project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investigation_project',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
