# Generated by Django 4.2.5 on 2023-10-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_investigation_project_id_product_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation_project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
