# Generated by Django 4.2.5 on 2023-10-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_donation_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.sponsor'),
        ),
    ]
