# Generated by Django 4.2.5 on 2023-10-15 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_investigation_project_id'),
        ('core', '0019_alter_donation_sponsor'),
    ]

    operations = [
    ]
