# Generated by Django 4.2.5 on 2023-10-15 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20231015_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='project',
            field=models.ForeignKey(db_constraint='false', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.investigation_project'),
        ),
    ]
