# Generated by Django 4.2.5 on 2023-10-15 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_product_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.investigation_project'),
        ),
    ]
